/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import ConexaoDAO.Conexaobd;
import ConexaoDAO.UserDAO;
import DTO.UserDTO;
import java.awt.Component;
import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gabi/sabino/diego
 */
public class Animals extends javax.swing.JFrame {

    /**
     * Creates new form CadAdotadorVIEW
     */
    public Animals() {
        initComponents();
        listarUsuarios();
        //listarUsua();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        tablePane = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        jScrollPane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        side_pane1.setBackground(new java.awt.Color(255, 255, 255));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 210));

        tablePane.setBackground(new java.awt.Color(255, 255, 255));

        tableUsuarios.setBackground(new java.awt.Color(243, 218, 202));
        tableUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Animal", "Adotante", "status"
            }
        ));
        tablePane.setViewportView(tableUsuarios);

        side_pane1.add(tablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 710, 350));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane.setViewportView(jList1);

        side_pane1.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, 100));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        side_pane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 630, 90));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        side_pane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(side_pane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animals().setVisible(true);
            }
        });
    }
    
    private void listarUsuarios() {
        try {
        Conexaobd conn = new Conexaobd();
        UserDAO obj = new UserDAO();

        DefaultTableModel model = (DefaultTableModel) tableUsuarios.getModel();
        
        model.setNumRows(0);

        ArrayList<UserDTO> lista = obj.listarUsuarios(conn.conebd());
        List<String[]> sqlTable = new ArrayList<String[]>();

        for (int num = 0; num < lista.size(); num++) {
            model.addRow(new Object[]{
            lista.get(num).getNome(),
            lista.get(num).getEmail(),
            });
        }
        
        for (int num = 0; num < lista.size(); num++) {
            sqlTable.add(new String[]{
            lista.get(num).getNome(),
            });
        }
        
        JList list = new JList(sqlTable.toArray());
        list.setCellRenderer(new ListCellRenderer() {

 
       public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            String[] val = (String[]) value;
            return new JLabel(val[0]);
            }
        });
        
        JScrollPane listScrollPane = new JScrollPane(list);
        jScrollPane.add(listScrollPane);

        jScrollPane.setSize(100, 100);
        jScrollPane.setVisible(true);
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar Usuários "+ erro);
        }
    }
    
    private void listarUsua() {
        String name;
       
        try {
        Conexaobd conn = new Conexaobd();
        UserDAO obj = new UserDAO();

        DefaultTableModel model = (DefaultTableModel) tableUsuarios.getModel();
        
        model.setNumRows(0);

        List<String[]> sqlTable = new ArrayList<String[]>();
        ArrayList<UserDTO> lista = obj.listarUsuarios(conn.conebd());

        for (int num = 0; num < lista.size(); num++) {
            sqlTable.add(new String[]{
            lista.get(num).getNome(),
            lista.get(num).getEmail(),
            });
        }
        
        JList list = new JList(sqlTable.toArray());
        list.setCellRenderer(new ListCellRenderer() {

 
       public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            String[] val = (String[]) value;
            return new JLabel(val[0]);
            }
        });
        
        JScrollPane listScrollPane = new JScrollPane(list);
       jScrollPane.add(listScrollPane);
        JFrame fr = new JFrame("Test)");

        fr.add(listScrollPane);

        fr.setSize(100, 100);
        fr.setVisible(true);


        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar Usuários "+ erro);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel logo2;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JTable tableUsuarios;
    // End of variables declaration//GEN-END:variables
}
