/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import ConexaoDAO.AdocoesDAO;
import ConexaoDAO.AnimalDAO;
import ConexaoDAO.Conexaobd;
import ConexaoDAO.UserDAO;
import DTO.AdocaoDTO;
import DTO.AnimalDTO;
import DTO.UserDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gabi/sabino/diego
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form CadAdotadorVIEW
     */
    public DashBoard() {
        initComponents();
        listarAdocoes();
        //listarUsua();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        javax.swing.JButton Sair = new javax.swing.JButton();
        btnCadastro1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        opStatus = new javax.swing.JComboBox<>();
        tablePane = new javax.swing.JScrollPane();
        tableAdocoes = new javax.swing.JTable();
        javax.swing.JButton btnNovo1 = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        side_pane1.setBackground(new java.awt.Color(255, 255, 255));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 210));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("DashBoard");
        side_pane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 290, -1));

        Sair.setBackground(new java.awt.Color(255, 51, 51));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setToolTipText("");
        Sair.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        side_pane1.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 50, -1));

        btnCadastro1.setBackground(new java.awt.Color(141, 103, 71));
        btnCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastro1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro1.setText("Atualizar Status");
        btnCadastro1.setToolTipText("");
        btnCadastro1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastro1ActionPerformed(evt);
            }
        });
        side_pane1.add(btnCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 260, 50));

        txtId.setBackground(new java.awt.Color(243, 218, 202));
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(102, 102, 102));
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId(evt);
            }
        });
        side_pane1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 200, 47));

        jPanel4.setBackground(new java.awt.Color(243, 218, 202));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        side_pane1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 90, 47));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Id da adoção");
        side_pane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        opStatus.setBackground(new java.awt.Color(255, 255, 255));
        opStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opStatus.setForeground(new java.awt.Color(102, 102, 102));
        opStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprovado", "Não Aprovado" }));
        opStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 218, 202), 3));
        opStatus.setFocusable(false);
        opStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opStatusActionPerformed(evt);
            }
        });
        side_pane1.add(opStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 220, 50));

        tablePane.setBackground(new java.awt.Color(62, 120, 198));
        tablePane.setForeground(new java.awt.Color(204, 204, 0));

        tableAdocoes.setBackground(new java.awt.Color(255, 255, 255));
        tableAdocoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableAdocoes.setForeground(new java.awt.Color(51, 51, 51));
        tableAdocoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Animal", "Adotante", "status"
            }
        ));
        tableAdocoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableAdocoes.setRowHeight(30);
        tablePane.setViewportView(tableAdocoes);

        side_pane1.add(tablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1030, 380));

        btnNovo1.setBackground(new java.awt.Color(223, 151, 107));
        btnNovo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNovo1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo1.setText("Novo Animal");
        btnNovo1.setToolTipText("");
        btnNovo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });
        side_pane1.add(btnNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 190, 50));

        logo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logo1.setForeground(new java.awt.Color(255, 255, 255));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/images/dashboard_bkgd.png"))); // NOI18N
        logo1.setText("    ");
        side_pane1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1160, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        Login dash = new Login();
        dispose();
        dash.setVisible(true); 
        
        UserDAO obj = new UserDAO();
        obj.logout();
        
        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso");
    }//GEN-LAST:event_SairActionPerformed

    private void btnCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastro1ActionPerformed
        String id, statusTX;
        Boolean status = false;

        id = txtId.getText();
        statusTX = opStatus.getSelectedItem().toString();
        
        if(statusTX.equals("Aprovado")){
            status = true;
        }
        if(statusTX.equals("Não Aprovado")){
            status = false;
        }
        
        try {
            AdocaoDTO objAdocaoDTO = new AdocaoDTO();
            objAdocaoDTO.setId(id);
            objAdocaoDTO.setStatus(status);

            AdocoesDAO obj = new AdocoesDAO();
            obj.aprovarAdocao(objAdocaoDTO);
      
        listarAdocoes();

        } catch (Exception  e) {
            JOptionPane.showMessageDialog(null, "Um erro aconteceu revise os campos e tente novamente");
        }
    }//GEN-LAST:event_btnCadastro1ActionPerformed

    private void txtId(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId

    private void opStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opStatusActionPerformed

    }//GEN-LAST:event_opStatusActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

  private void listarAdocoes() {
        try {
        Conexaobd conn = new Conexaobd();
        AdocoesDAO obj = new AdocoesDAO();

        DefaultTableModel model = (DefaultTableModel) tableAdocoes.getModel();
        
        model.setNumRows(0);

        ArrayList<AdocaoDTO> lista = obj.listarAdocoes(conn.conebd());
        List<String[]> sqlTable = new ArrayList<String[]>();

        for (int num = 0; num < lista.size(); num++) {
            model.addRow(new Object[]{
            lista.get(num).getId(),
            lista.get(num).getAnimal(),
            lista.get(num).getUsuario(),
            lista.get(num).isStatus(),
            });
        }
        tableAdocoes.setGridColor(Color.decode("#8D6747"));
        tableAdocoes.getTableHeader().setBackground(Color.decode("#8D6747"));
        tableAdocoes.getTableHeader().setForeground(Color.white);
        tableAdocoes.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        
        JList list = new JList(sqlTable.toArray());
        list.setCellRenderer(new ListCellRenderer() {
 
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                 String[] val = (String[]) value;
                 return new JLabel(val[0]);   
             }
       
        });
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar os Animais "+ erro);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JComboBox<String> opStatus;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JTable tableAdocoes;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
