/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import ConexaoDAO.AdocoesDAO;
import ConexaoDAO.AnimalDAO;
import ConexaoDAO.Conexaobd;
import ConexaoDAO.UserDAO;
import DTO.AdocaoDTO;
import DTO.AnimalDTO;
import DTO.UserDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gabi/sabino/diego
 */
public class ShwAnimais extends javax.swing.JFrame {

    /**
     * Creates new form CadAdotadorVIEW
     */
    public ShwAnimais() {
        initComponents();
        listarAnimais();
        //listarUsua();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        tablePane = new javax.swing.JScrollPane();
        tableAnimals = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        javax.swing.JButton Sair = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        side_pane1.setBackground(new java.awt.Color(255, 255, 255));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Disponíveis");
        side_pane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));
        side_pane1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 210));

        tablePane.setBackground(new java.awt.Color(62, 120, 198));
        tablePane.setForeground(new java.awt.Color(204, 204, 0));

        tableAnimals.setBackground(new java.awt.Color(255, 255, 255));
        tableAnimals.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableAnimals.setForeground(new java.awt.Color(51, 51, 51));
        tableAnimals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Animal", "Tipo", "Raça", "Descrição"
            }
        ));
        tableAnimals.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableAnimals.setRowHeight(30);
        tablePane.setViewportView(tableAnimals);

        side_pane1.add(tablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 730, 350));

        btnCadastro.setBackground(new java.awt.Color(141, 103, 71));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Solicitar Adoção");
        btnCadastro.setToolTipText("");
        btnCadastro.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        side_pane1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 260, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Animais");
        side_pane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 43, 39));
        jLabel8.setText("by: @gagonzaga, @petile & @gsabino");
        side_pane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 700, 190, 30));

        idInput.setBackground(new java.awt.Color(243, 218, 202));
        idInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idInput.setForeground(new java.awt.Color(102, 102, 102));
        idInput.setBorder(null);
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInput(evt);
            }
        });
        side_pane1.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 430, 47));

        jPanel4.setBackground(new java.awt.Color(243, 218, 202));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        side_pane1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 90, 47));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Id do Animal");
        side_pane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        Sair.setBackground(new java.awt.Color(255, 51, 51));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setToolTipText("");
        Sair.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        side_pane1.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 50, -1));

        logo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logo1.setForeground(new java.awt.Color(255, 255, 255));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/images/shwAni_bkgd.png"))); // NOI18N
        logo1.setText("    ");
        side_pane1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1160, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        String id;

        id = idInput.getText();
        
        System.out.println(id);
        
        Login usu = new Login();
        
        try {
            AdocaoDTO objAdocaoDTO= new AdocaoDTO();
            
            objAdocaoDTO.setId_animal(id);
            objAdocaoDTO.setId_adotante("1");
            
            System.out.println(usu.getUserId());

            AdocoesDAO obj = new AdocoesDAO();
            obj.cadastrar(objAdocaoDTO);
            
            Sucesso dash = new Sucesso();
            dispose();
            dash.setVisible(true);

      
        } catch (Exception  e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void idInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInput
        // TODO add your handling code here:
    }//GEN-LAST:event_idInput

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        Login dash = new Login();
        dispose();
        dash.setVisible(true);

        UserDAO obj = new UserDAO();
        obj.logout();

        JOptionPane.showMessageDialog(null, "Logout realizado com sucesso");
    }//GEN-LAST:event_SairActionPerformed

    public static void main(String args[]) {        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShwAnimais().setVisible(true);
            }
        });
    }

  private void listarAnimais() {
        try {
        Conexaobd conn = new Conexaobd();
        AnimalDAO obj = new AnimalDAO();

        DefaultTableModel model = (DefaultTableModel) tableAnimals.getModel();

        ArrayList<AnimalDTO> lista = obj.listarAnimais(conn.conebd());
        List<String[]> sqlTable = new ArrayList<String[]>();

        for (int num = 0; num < lista.size(); num++) {
            model.addRow(new Object[]{
                lista.get(num).getId(),
                lista.get(num).getNome(),
                lista.get(num).getRaca(),
                lista.get(num).getTipo(),
                lista.get(num).getDescricao()
            });
        }
        
        tableAnimals.setGridColor(Color.decode("#8D6747"));
        tableAnimals.getTableHeader().setBackground(Color.decode("#8D6747"));
        tableAnimals.getTableHeader().setForeground(Color.white);
        tableAnimals.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        
        JList list = new JList(sqlTable.toArray());
        list.setCellRenderer(new ListCellRenderer() {
 
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                 String[] val = (String[]) value;
                 return new JLabel(val[0]);   
             }
       
        });
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar os Animais "+ erro);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JTable tableAnimals;
    private javax.swing.JScrollPane tablePane;
    // End of variables declaration//GEN-END:variables
}
